# Generated by Django 3.1.5 on 2021-02-15 19:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(auto_now_add=True, verbose_name='Hire Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='in Lari / % (if being washer )', max_digits=8, verbose_name='Salary'),
        ),
    ]
