# Generated by Django 3.1.5 on 2021-02-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled time'),
        ),
    ]
