# Generated by Django 3.1.5 on 2021-02-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0002_auto_20210205_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End time'),
        ),
    ]
