# Generated by Django 3.1.5 on 2021-01-18 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=3, verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Book Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Added Date/Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date/Time')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Stock')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.authormodel')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),

    ]
