# Generated by Django 3.1.5 on 2021-01-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorModel',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='BookModel',
            new_name='Book',
        ),
    ]
