# Generated by Django 3.1.5 on 2021-01-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_location_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.CreateModel(
            name='StoreToBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_to_books', to='store.book')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_to_books', to='store.store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='stores', through='store.StoreToBook', to='store.Book'),
        ),
    ]
