# Generated by Django 3.1.5 on 2021-01-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210122_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetobook',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
